server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location ^~ /_expo/ {
        try_files $uri =404;
    }

    location ~ ^/.+/_expo/(.*)$ {
        try_files /_expo/$1 =404;
    }

    location ^~ /assets/ {
        try_files $uri =404;
    }

    location ~ ^/.+/assets/(.*)$ {
        try_files /assets/$1 =404;
    }

    location ^~ /.well-known/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri.html $uri/index.html $uri/index.htm $uri/ /index.html =404;
    }

    error_page 404 /index.html;
}
