/**
 * useTaskImport
 *
 * Data-layer hook for importing tasks from cached snapshots of other (possibly
 * dead) teams into the current team's board.
 *
 * Responsibilities:
 * 1. Load all cached snapshots that are NOT for the current team.
 * 2. Expose them as `availableSnapshots` grouped by team.
 * 3. Analyse a selected set of ExportedTasks against the current board to
 *    surface imported / skipped / conflicted tasks.
 * 4. Execute the import: generate new KanbanTask objects and call the caller-
 *    supplied `onImport` handler to persist them.
 *
 * What this hook does NOT do:
 * - UI rendering (that is TaskImportModal's job)
 * - Direct persistence (callers own the board state)
 * - Column/status remapping (exposed via `mapStatus` utility; callers decide)
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
    loadAllTaskExportSnapshots,
    analyseImport,
    toKanbanTask,
    type ExportedTask,
    type TaskExportSnapshot,
    type TaskImportResult,
} from '@/sync/taskExportCache';
import type { KanbanTask, KanbanColumn } from '@/sync/kanbanTypes';

// ─── Types ────────────────────────────────────────────────────────────────────

/** Policy for handling conflict tasks (same id, different content). */
export type ConflictResolutionPolicy =
    | 'skip'       // keep existing, discard incoming (default)
    | 'overwrite'  // replace existing with incoming
    | 'rename';    // import incoming under a new id (generated by caller)

export interface ImportOptions {
    /** Which tasks from the selected snapshot to import (default: all tasks). */
    taskIds?: string[];
    /** How to handle tasks whose id already exists on the board. @default 'skip' */
    conflictPolicy?: ConflictResolutionPolicy;
    /**
     * Map an exported task's `status` to a valid column id on the target board.
     * Falls back to the first column when the exported status does not match any
     * column in the target board.
     */
    statusMap?: Record<string, string>;
}

export interface ImportSummary extends TaskImportResult {
    /** Final KanbanTask objects that were handed to `onImport`. */
    added: KanbanTask[];
}

export interface UseTaskImportOptions {
    /** The team currently open — its cached snapshot is excluded from the list. */
    currentTeamId: string;
    /** All tasks currently on the board (used for conflict detection). */
    existingTasks: KanbanTask[];
    /** Column definitions of the target board (used for status mapping). */
    targetColumns: KanbanColumn[];
    /**
     * Called when the user confirms an import.
     * Receives an array of new KanbanTask objects to add to the board.
     * Callers are responsible for persisting them (e.g. via the team API).
     */
    onImport: (tasks: KanbanTask[]) => Promise<void> | void;
}

export interface UseTaskImportResult {
    /** Snapshots from all other teams stored in MMKV, newest first. */
    availableSnapshots: TaskExportSnapshot[];
    /** True while the snapshot list is being loaded from MMKV. */
    isLoading: boolean;
    /**
     * Analyse what would happen if `tasks` were imported.
     * Does NOT mutate any state — purely informational.
     */
    previewImport: (tasks: ExportedTask[]) => TaskImportResult;
    /**
     * Execute the import: analyse, apply conflict policy, call `onImport`.
     * Returns a summary of what was added / skipped / conflicted.
     */
    executeImport: (
        snapshot: TaskExportSnapshot,
        options?: ImportOptions
    ) => Promise<ImportSummary>;
    /** Force-reload the available snapshots from MMKV. */
    refresh: () => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Map an exported status to a valid column id on the target board.
 * Falls back to the first column when no match is found.
 */
export function mapStatus(
    exportedStatus: string,
    targetColumns: KanbanColumn[],
    customMap?: Record<string, string>
): string {
    if (customMap?.[exportedStatus]) return customMap[exportedStatus];
    const exact = targetColumns.find(c => c.id === exportedStatus);
    if (exact) return exact.id;
    return targetColumns[0]?.id ?? 'todo';
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

export function useTaskImport({
    currentTeamId,
    existingTasks,
    targetColumns,
    onImport,
}: UseTaskImportOptions): UseTaskImportResult {
    const [availableSnapshots, setAvailableSnapshots] = useState<TaskExportSnapshot[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    // ── Load snapshots on mount and when currentTeamId changes ─────────────

    const loadSnapshots = useCallback(() => {
        setIsLoading(true);
        const snapshots = loadAllTaskExportSnapshots({ excludeTeamId: currentTeamId });
        setAvailableSnapshots(snapshots);
        setIsLoading(false);
    }, [currentTeamId]);

    useEffect(() => {
        loadSnapshots();
    }, [loadSnapshots]);

    // ── Preview (pure analysis, no side effects) ────────────────────────────

    const previewImport = useCallback(
        (tasks: ExportedTask[]): TaskImportResult =>
            analyseImport(tasks, existingTasks),
        [existingTasks]
    );

    // ── Execute import ──────────────────────────────────────────────────────

    const executeImport = useCallback(
        async (
            snapshot: TaskExportSnapshot,
            options: ImportOptions = {}
        ): Promise<ImportSummary> => {
            const {
                taskIds,
                conflictPolicy = 'skip',
                statusMap,
            } = options;

            // Filter tasks if specific ids were requested.
            const tasksToProcess = taskIds
                ? snapshot.tasks.filter(t => taskIds.includes(t.id))
                : snapshot.tasks;

            const analysis = analyseImport(tasksToProcess, existingTasks);
            const toAdd: KanbanTask[] = [];

            // Cleanly imported tasks — map status and add.
            for (const exported of analysis.imported) {
                const mappedStatus = mapStatus(exported.status, targetColumns, statusMap);
                toAdd.push(toKanbanTask(exported, { status: mappedStatus }));
            }

            // Conflicted tasks — apply resolution policy.
            for (const { incoming } of analysis.conflicts) {
                if (conflictPolicy === 'overwrite') {
                    const mappedStatus = mapStatus(incoming.status, targetColumns, statusMap);
                    toAdd.push(toKanbanTask(incoming, { status: mappedStatus }));
                }
                // 'skip': do nothing
                // 'rename': caller handles by providing a custom id via taskIds filter
            }

            if (toAdd.length > 0) {
                await onImport(toAdd);
            }

            return { ...analysis, added: toAdd };
        },
        [existingTasks, targetColumns, onImport]
    );

    return {
        availableSnapshots,
        isLoading,
        previewImport,
        executeImport,
        refresh: loadSnapshots,
    };
}
