import * as React from "react";
import { View } from "react-native";
import { Image } from "expo-image";

interface AvatarBrutalistProps {
    id: string;
    title?: boolean;
    square?: boolean;
    size?: number;
    monochrome?: boolean;
}

const abstractImages = [
    require('@/assets/images/brutalist/Abstract_1.png'),
    require('@/assets/images/brutalist/Abstract_2.png'),
    require('@/assets/images/brutalist/Abstract_3.png'),
    require('@/assets/images/brutalist/Abstract_4.png'),
    require('@/assets/images/brutalist/Abstract_5.png'),
    require('@/assets/images/brutalist/Abstract_6.png'),
    require('@/assets/images/brutalist/Abstract_7.png'),
    require('@/assets/images/brutalist/Abstract_8.png'),
    require('@/assets/images/brutalist/Abstract_9.png'),
    require('@/assets/images/brutalist/Abstract_10.png'),
    require('@/assets/images/brutalist/Abstract_11.png'),
    require('@/assets/images/brutalist/Abstract_12.png'),
    require('@/assets/images/brutalist/Abstract_13.png'),
    require('@/assets/images/brutalist/Abstract_14.png'),
    require('@/assets/images/brutalist/Abstract_15.png'),
    require('@/assets/images/brutalist/Abstract_16.png'),
    require('@/assets/images/brutalist/Abstract_17.png'),
    require('@/assets/images/brutalist/Abstract_18.png'),
    require('@/assets/images/brutalist/Abstract_19.png'),
    require('@/assets/images/brutalist/Abstract_20.png'),
    require('@/assets/images/brutalist/Abstract_21.png'),
    require('@/assets/images/brutalist/Abstract_22.png'),
    require('@/assets/images/brutalist/Abstract_23.png'),
    require('@/assets/images/brutalist/Abstract_24.png'),
    require('@/assets/images/brutalist/Abstract_25.png'),
    require('@/assets/images/brutalist/Abstract_26.png'),
    require('@/assets/images/brutalist/Abstract_27.png'),
    require('@/assets/images/brutalist/Abstract_28.png'),
    require('@/assets/images/brutalist/Abstract_29.png'),
    require('@/assets/images/brutalist/Abstract_30.png'),
    require('@/assets/images/brutalist/Abstract_31.png'),
    require('@/assets/images/brutalist/Abstract_32.png'),
    require('@/assets/images/brutalist/Abstract_33.png'),
    require('@/assets/images/brutalist/Abstract_34.png'),
    require('@/assets/images/brutalist/Abstract_35.png'),
    require('@/assets/images/brutalist/Abstract_36.png'),
    require('@/assets/images/brutalist/Abstract_37.png'),
    require('@/assets/images/brutalist/Abstract_38.png'),
    require('@/assets/images/brutalist/Abstract_39.png'),
    require('@/assets/images/brutalist/Abstract_40.png'),
    require('@/assets/images/brutalist/Abstract_41.png'),
    require('@/assets/images/brutalist/Abstract_42.png'),
    require('@/assets/images/brutalist/Abstract_43.png'),
    require('@/assets/images/brutalist/Abstract_44.png'),
    require('@/assets/images/brutalist/Abstract_45.png'),
    require('@/assets/images/brutalist/Abstract_46.png'),
    require('@/assets/images/brutalist/Abstract_47.png'),
    require('@/assets/images/brutalist/Abstract_48.png'),
    require('@/assets/images/brutalist/Abstract_49.png'),
    require('@/assets/images/brutalist/Abstract_50.png'),
    require('@/assets/images/brutalist/Abstract_51.png'),
    require('@/assets/images/brutalist/Abstract_52.png'),
    require('@/assets/images/brutalist/Abstract_53.png'),
    require('@/assets/images/brutalist/Abstract_54.png'),
    require('@/assets/images/brutalist/Abstract_55.png'),
    require('@/assets/images/brutalist/Abstract_56.png'),
    require('@/assets/images/brutalist/Abstract_57.png'),
    require('@/assets/images/brutalist/Abstract_58.png'),
    require('@/assets/images/brutalist/Abstract_59.png'),
    require('@/assets/images/brutalist/Abstract_60.png'),
    require('@/assets/images/brutalist/Abstract_61.png'),
    require('@/assets/images/brutalist/Abstract_62.png'),
    require('@/assets/images/brutalist/Abstract_63.png'),
    require('@/assets/images/brutalist/Abstract_64.png'),
    require('@/assets/images/brutalist/Abstract_65.png'),
    require('@/assets/images/brutalist/Abstract_66.png'),
    require('@/assets/images/brutalist/Abstract_67.png'),
    require('@/assets/images/brutalist/Abstract_68.png'),
    require('@/assets/images/brutalist/Abstract_69.png'),
    require('@/assets/images/brutalist/Abstract_70.png'),
    require('@/assets/images/brutalist/Abstract_71.png'),
    require('@/assets/images/brutalist/Abstract_72.png'),
    require('@/assets/images/brutalist/Abstract_73.png'),
    require('@/assets/images/brutalist/Abstract_74.png'),
    require('@/assets/images/brutalist/Abstract_75.png'),
    require('@/assets/images/brutalist/Abstract_76.png'),
    require('@/assets/images/brutalist/Abstract_77.png'),
    require('@/assets/images/brutalist/Abstract_78.png'),
    require('@/assets/images/brutalist/Abstract_79.png'),
    require('@/assets/images/brutalist/Abstract_80.png'),
    require('@/assets/images/brutalist/Abstract_81.png'),
    require('@/assets/images/brutalist/Abstract_82.png'),
    require('@/assets/images/brutalist/Abstract_83.png'),
    require('@/assets/images/brutalist/Abstract_84.png'),
    require('@/assets/images/brutalist/Abstract_85.png'),
    require('@/assets/images/brutalist/Abstract_86.png'),
    require('@/assets/images/brutalist/Abstract_87.png'),
    require('@/assets/images/brutalist/Abstract_88.png'),
    require('@/assets/images/brutalist/Abstract_89.png'),
    require('@/assets/images/brutalist/Abstract_90.png'),
    require('@/assets/images/brutalist/Abstract_91.png'),
    require('@/assets/images/brutalist/Abstract_92.png'),
    require('@/assets/images/brutalist/Abstract_93.png'),
    require('@/assets/images/brutalist/Abstract_94.png'),
    require('@/assets/images/brutalist/Abstract_95.png'),
    require('@/assets/images/brutalist/Abstract_96.png'),
    require('@/assets/images/brutalist/Abstract_97.png'),
    require('@/assets/images/brutalist/Abstract_98.png'),
    require('@/assets/images/brutalist/Abstract_99.png'),
    require('@/assets/images/brutalist/Abstract_100.png'),
    require('@/assets/images/brutalist/Abstract_101.png'),
    require('@/assets/images/brutalist/Abstract_102.png'),
    require('@/assets/images/brutalist/Abstract_103.png'),
    require('@/assets/images/brutalist/Abstract_104.png'),
    require('@/assets/images/brutalist/Abstract_105.png'),
    require('@/assets/images/brutalist/Abstract_106.png'),
    require('@/assets/images/brutalist/Abstract_107.png'),
    require('@/assets/images/brutalist/Abstract_108.png'),
    require('@/assets/images/brutalist/Abstract_109.png'),
    require('@/assets/images/brutalist/Abstract_110.png'),
    require('@/assets/images/brutalist/Abstract_111.png'),
    require('@/assets/images/brutalist/Abstract_112.png'),
    require('@/assets/images/brutalist/Abstract_113.png'),
    require('@/assets/images/brutalist/Abstract_114.png'),
    require('@/assets/images/brutalist/Abstract_115.png'),
    require('@/assets/images/brutalist/Abstract_116.png'),
    require('@/assets/images/brutalist/Abstract_117.png'),
    require('@/assets/images/brutalist/Abstract_118.png'),
    require('@/assets/images/brutalist/Abstract_119.png'),
    require('@/assets/images/brutalist/Abstract_120.png'),
    require('@/assets/images/brutalist/Abstract_121.png'),
    require('@/assets/images/brutalist/Abstract_122.png'),
    require('@/assets/images/brutalist/Abstract_123.png'),
    require('@/assets/images/brutalist/Abstract_124.png'),
    require('@/assets/images/brutalist/Abstract_125.png'),
    require('@/assets/images/brutalist/Abstract_126.png'),
    require('@/assets/images/brutalist/Abstract_127.png'),
    require('@/assets/images/brutalist/Abstract_128.png'),
    require('@/assets/images/brutalist/Abstract_129.png'),
    require('@/assets/images/brutalist/Abstract_130.png'),
    require('@/assets/images/brutalist/Abstract_131.png'),
    require('@/assets/images/brutalist/Abstract_132.png'),
    require('@/assets/images/brutalist/Abstract_133.png'),
    require('@/assets/images/brutalist/Abstract_134.png'),
    require('@/assets/images/brutalist/Abstract_135.png'),
    require('@/assets/images/brutalist/Abstract_136.png'),
    require('@/assets/images/brutalist/Abstract_137.png'),
    require('@/assets/images/brutalist/Abstract_138.png'),
    require('@/assets/images/brutalist/Abstract_139.png'),
    require('@/assets/images/brutalist/Abstract_140.png'),
    require('@/assets/images/brutalist/Abstract_141.png'),
    require('@/assets/images/brutalist/Abstract_142.png'),
    require('@/assets/images/brutalist/Abstract_143.png'),
    require('@/assets/images/brutalist/Abstract_144.png'),
    require('@/assets/images/brutalist/Abstract_145.png'),
    require('@/assets/images/brutalist/Abstract_146.png'),
    require('@/assets/images/brutalist/Abstract_147.png'),
    require('@/assets/images/brutalist/Abstract_148.png'),
    require('@/assets/images/brutalist/Abstract_149.png'),
    require('@/assets/images/brutalist/Abstract_150.png'),
    require('@/assets/images/brutalist/Abstract_151.png'),
    require('@/assets/images/brutalist/Abstract_152.png'),
    require('@/assets/images/brutalist/Abstract_153.png'),
    require('@/assets/images/brutalist/Abstract_154.png'),
    require('@/assets/images/brutalist/Abstract_155.png'),
    require('@/assets/images/brutalist/Abstract_156.png'),
    require('@/assets/images/brutalist/Abstract_157.png'),
    require('@/assets/images/brutalist/Abstract_158.png'),
    require('@/assets/images/brutalist/Abstract_159.png'),
    require('@/assets/images/brutalist/Abstract_160.png'),
    require('@/assets/images/brutalist/Abstract_161.png'),
    require('@/assets/images/brutalist/Abstract_162.png'),
    require('@/assets/images/brutalist/Abstract_163.png'),
    require('@/assets/images/brutalist/Abstract_164.png'),
    require('@/assets/images/brutalist/Abstract_165.png'),
    require('@/assets/images/brutalist/Abstract_166.png'),
    require('@/assets/images/brutalist/Abstract_167.png'),
    require('@/assets/images/brutalist/Abstract_168.png'),
    require('@/assets/images/brutalist/Abstract_169.png'),
    require('@/assets/images/brutalist/Abstract_170.png'),
    require('@/assets/images/brutalist/Abstract_171.png'),
    require('@/assets/images/brutalist/Abstract_172.png'),
    require('@/assets/images/brutalist/Abstract_173.png'),
    require('@/assets/images/brutalist/Abstract_174.png'),
    require('@/assets/images/brutalist/Abstract_175.png'),
    require('@/assets/images/brutalist/Abstract_176.png'),
    require('@/assets/images/brutalist/Abstract_177.png'),
    require('@/assets/images/brutalist/Abstract_178.png'),
    require('@/assets/images/brutalist/Abstract_179.png'),
    require('@/assets/images/brutalist/Abstract_180.png'),
    require('@/assets/images/brutalist/Abstract_181.png'),
    require('@/assets/images/brutalist/Abstract_182.png'),
    require('@/assets/images/brutalist/Abstract_183.png'),
    require('@/assets/images/brutalist/Abstract_184.png'),
    require('@/assets/images/brutalist/Abstract_185.png'),
    require('@/assets/images/brutalist/Abstract_186.png'),
    require('@/assets/images/brutalist/Abstract_187.png'),
    require('@/assets/images/brutalist/Abstract_188.png'),
    require('@/assets/images/brutalist/Abstract_189.png'),
    require('@/assets/images/brutalist/Abstract_190.png'),
    require('@/assets/images/brutalist/Abstract_191.png'),
    require('@/assets/images/brutalist/Abstract_192.png'),
    require('@/assets/images/brutalist/Abstract_193.png'),
    require('@/assets/images/brutalist/Abstract_194.png'),
    require('@/assets/images/brutalist/Abstract_195.png'),
    require('@/assets/images/brutalist/Abstract_196.png'),
    require('@/assets/images/brutalist/Abstract_197.png'),
    require('@/assets/images/brutalist/Abstract_198.png'),
    require('@/assets/images/brutalist/Abstract_199.png'),
    require('@/assets/images/brutalist/Abstract_200.png'),
    require('@/assets/images/brutalist/Abstract_201.png'),
    require('@/assets/images/brutalist/Abstract_202.png'),
    require('@/assets/images/brutalist/Abstract_203.png'),
    require('@/assets/images/brutalist/Abstract_204.png'),
    require('@/assets/images/brutalist/Abstract_205.png'),
    require('@/assets/images/brutalist/Abstract_206.png'),
    require('@/assets/images/brutalist/Abstract_207.png'),
    require('@/assets/images/brutalist/Abstract_208.png'),
    require('@/assets/images/brutalist/Abstract_209.png'),
    require('@/assets/images/brutalist/Abstract_210.png'),
    require('@/assets/images/brutalist/Abstract_211.png'),
    require('@/assets/images/brutalist/Abstract_212.png'),
    require('@/assets/images/brutalist/Abstract_213.png'),
    require('@/assets/images/brutalist/Abstract_214.png'),
    require('@/assets/images/brutalist/Abstract_215.png'),
    require('@/assets/images/brutalist/Abstract_216.png'),
    require('@/assets/images/brutalist/Abstract_217.png'),
    require('@/assets/images/brutalist/Abstract_218.png'),
    require('@/assets/images/brutalist/Abstract_219.png'),
    require('@/assets/images/brutalist/Abstract_220.png'),
    require('@/assets/images/brutalist/Abstract_221.png'),
    require('@/assets/images/brutalist/Abstract_222.png'),
    require('@/assets/images/brutalist/Abstract_223.png'),
    require('@/assets/images/brutalist/Abstract_224.png'),
    require('@/assets/images/brutalist/Abstract_225.png'),
    require('@/assets/images/brutalist/Abstract_226.png'),
    require('@/assets/images/brutalist/Abstract_227.png'),
    require('@/assets/images/brutalist/Abstract_228.png'),
    require('@/assets/images/brutalist/Abstract_229.png'),
    require('@/assets/images/brutalist/Abstract_230.png'),
    require('@/assets/images/brutalist/Abstract_231.png'),
    require('@/assets/images/brutalist/Abstract_232.png'),
    require('@/assets/images/brutalist/Abstract_233.png'),
    require('@/assets/images/brutalist/Abstract_234.png'),
    require('@/assets/images/brutalist/Abstract_235.png'),
    require('@/assets/images/brutalist/Abstract_236.png'),
    require('@/assets/images/brutalist/Abstract_237.png'),
    require('@/assets/images/brutalist/Abstract_238.png'),
    require('@/assets/images/brutalist/Abstract_239.png'),
    require('@/assets/images/brutalist/Abstract_240.png'),
    require('@/assets/images/brutalist/Abstract_241.png'),
    require('@/assets/images/brutalist/Abstract_242.png'),
    require('@/assets/images/brutalist/Abstract_243.png'),
    require('@/assets/images/brutalist/Abstract_244.png'),
    require('@/assets/images/brutalist/Abstract_245.png'),
    require('@/assets/images/brutalist/Abstract_246.png'),
    require('@/assets/images/brutalist/Abstract_247.png'),
    require('@/assets/images/brutalist/Abstract_248.png'),
    require('@/assets/images/brutalist/Abstract_249.png'),
    require('@/assets/images/brutalist/Abstract_250.png'),
    require('@/assets/images/brutalist/Abstract_251.png'),
    require('@/assets/images/brutalist/Abstract_252.png'),
    require('@/assets/images/brutalist/Abstract_253.png'),
    require('@/assets/images/brutalist/Abstract_254.png'),
    require('@/assets/images/brutalist/Abstract_255.png'),
    require('@/assets/images/brutalist/Abstract_256.png'),
    require('@/assets/images/brutalist/Abstract_257.png'),
    require('@/assets/images/brutalist/Abstract_258.png'),
    require('@/assets/images/brutalist/Abstract_259.png'),
    require('@/assets/images/brutalist/Abstract_260.png'),
    require('@/assets/images/brutalist/Abstract_261.png'),
    require('@/assets/images/brutalist/Abstract_262.png'),
];

const bauhausImages = [
    require('@/assets/images/brutalist/Bauhaus_1.png'),
    require('@/assets/images/brutalist/Bauhaus_2.png'),
    require('@/assets/images/brutalist/Bauhaus_3.png'),
    require('@/assets/images/brutalist/Bauhaus_4.png'),
    require('@/assets/images/brutalist/Bauhaus_5.png'),
    require('@/assets/images/brutalist/Bauhaus_6.png'),
    require('@/assets/images/brutalist/Bauhaus_7.png'),
    require('@/assets/images/brutalist/Bauhaus_8.png'),
    require('@/assets/images/brutalist/Bauhaus_9.png'),
    require('@/assets/images/brutalist/Bauhaus_10.png'),
    require('@/assets/images/brutalist/Bauhaus_11.png'),
    require('@/assets/images/brutalist/Bauhaus_12.png'),
    require('@/assets/images/brutalist/Bauhaus_13.png'),
    require('@/assets/images/brutalist/Bauhaus_14.png'),
    require('@/assets/images/brutalist/Bauhaus_15.png'),
    require('@/assets/images/brutalist/Bauhaus_16.png'),
    require('@/assets/images/brutalist/Bauhaus_17.png'),
    require('@/assets/images/brutalist/Bauhaus_18.png'),
    require('@/assets/images/brutalist/Bauhaus_19.png'),
    require('@/assets/images/brutalist/Bauhaus_20.png'),
    require('@/assets/images/brutalist/Bauhaus_21.png'),
    require('@/assets/images/brutalist/Bauhaus_22.png'),
    require('@/assets/images/brutalist/Bauhaus_23.png'),
    require('@/assets/images/brutalist/Bauhaus_24.png'),
    require('@/assets/images/brutalist/Bauhaus_25.png'),
    require('@/assets/images/brutalist/Bauhaus_26.png'),
    require('@/assets/images/brutalist/Bauhaus_27.png'),
    require('@/assets/images/brutalist/Bauhaus_28.png'),
    require('@/assets/images/brutalist/Bauhaus_29.png'),
    require('@/assets/images/brutalist/Bauhaus_30.png'),
    require('@/assets/images/brutalist/Bauhaus_31.png'),
    require('@/assets/images/brutalist/Bauhaus_32.png'),
    require('@/assets/images/brutalist/Bauhaus_33.png'),
    require('@/assets/images/brutalist/Bauhaus_34.png'),
    require('@/assets/images/brutalist/Bauhaus_35.png'),
    require('@/assets/images/brutalist/Bauhaus_36.png'),
    require('@/assets/images/brutalist/Bauhaus_37.png'),
    require('@/assets/images/brutalist/Bauhaus_38.png'),
    require('@/assets/images/brutalist/Bauhaus_39.png'),
    require('@/assets/images/brutalist/Bauhaus_40.png'),
];

const brutalismImages = [
    require('@/assets/images/brutalist/Brutalism_1.png'),
    require('@/assets/images/brutalist/Brutalism_2.png'),
    require('@/assets/images/brutalist/Brutalism_3.png'),
    require('@/assets/images/brutalist/Brutalism_4.png'),
    require('@/assets/images/brutalist/Brutalism_5.png'),
    require('@/assets/images/brutalist/Brutalism_6.png'),
    require('@/assets/images/brutalist/Brutalism_7.png'),
    require('@/assets/images/brutalist/Brutalism_8.png'),
    require('@/assets/images/brutalist/Brutalism_9.png'),
    require('@/assets/images/brutalist/Brutalism_10.png'),
    require('@/assets/images/brutalist/Brutalism_11.png'),
    require('@/assets/images/brutalist/Brutalism_12.png'),
    require('@/assets/images/brutalist/Brutalism_13.png'),
    require('@/assets/images/brutalist/Brutalism_14.png'),
    require('@/assets/images/brutalist/Brutalism_15.png'),
    require('@/assets/images/brutalist/Brutalism_16.png'),
    require('@/assets/images/brutalist/Brutalism_17.png'),
    require('@/assets/images/brutalist/Brutalism_18.png'),
    require('@/assets/images/brutalist/Brutalism_19.png'),
    require('@/assets/images/brutalist/Brutalism_20.png'),
    require('@/assets/images/brutalist/Brutalism_21.png'),
    require('@/assets/images/brutalist/Brutalism_22.png'),
    require('@/assets/images/brutalist/Brutalism_23.png'),
    require('@/assets/images/brutalist/Brutalism_24.png'),
    require('@/assets/images/brutalist/Brutalism_25.png'),
    require('@/assets/images/brutalist/Brutalism_26.png'),
    require('@/assets/images/brutalist/Brutalism_27.png'),
    require('@/assets/images/brutalist/Brutalism_28.png'),
    require('@/assets/images/brutalist/Brutalism_29.png'),
    require('@/assets/images/brutalist/Brutalism_30.png'),
    require('@/assets/images/brutalist/Brutalism_31.png'),
    require('@/assets/images/brutalist/Brutalism_32.png'),
    require('@/assets/images/brutalist/Brutalism_33.png'),
    require('@/assets/images/brutalist/Brutalism_34.png'),
    require('@/assets/images/brutalist/Brutalism_35.png'),
    require('@/assets/images/brutalist/Brutalism_36.png'),
    require('@/assets/images/brutalist/Brutalism_37.png'),
    require('@/assets/images/brutalist/Brutalism_38.png'),
    require('@/assets/images/brutalist/Brutalism_39.png'),
    require('@/assets/images/brutalist/Brutalism_40.png'),
    require('@/assets/images/brutalist/Brutalism_41.png'),
    require('@/assets/images/brutalist/Brutalism_42.png'),
    require('@/assets/images/brutalist/Brutalism_43.png'),
    require('@/assets/images/brutalist/Brutalism_44.png'),
    require('@/assets/images/brutalist/Brutalism_45.png'),
    require('@/assets/images/brutalist/Brutalism_46.png'),
    require('@/assets/images/brutalist/Brutalism_47.png'),
    require('@/assets/images/brutalist/Brutalism_48.png'),
    require('@/assets/images/brutalist/Brutalism_49.png'),
    require('@/assets/images/brutalist/Brutalism_50.png'),
    require('@/assets/images/brutalist/Brutalism_51.png'),
    require('@/assets/images/brutalist/Brutalism_52.png'),
    require('@/assets/images/brutalist/Brutalism_53.png'),
    require('@/assets/images/brutalist/Brutalism_54.png'),
    require('@/assets/images/brutalist/Brutalism_55.png'),
    require('@/assets/images/brutalist/Brutalism_56.png'),
    require('@/assets/images/brutalist/Brutalism_57.png'),
    require('@/assets/images/brutalist/Brutalism_58.png'),
    require('@/assets/images/brutalist/Brutalism_59.png'),
    require('@/assets/images/brutalist/Brutalism_60.png'),
    require('@/assets/images/brutalist/Brutalism_61.png'),
    require('@/assets/images/brutalist/Brutalism_62.png'),
    require('@/assets/images/brutalist/Brutalism_63.png'),
    require('@/assets/images/brutalist/Brutalism_64.png'),
    require('@/assets/images/brutalist/Brutalism_65.png'),
    require('@/assets/images/brutalist/Brutalism_66.png'),
    require('@/assets/images/brutalist/Brutalism_67.png'),
    require('@/assets/images/brutalist/Brutalism_68.png'),
    require('@/assets/images/brutalist/Brutalism_69.png'),
    require('@/assets/images/brutalist/Brutalism_70.png'),
    require('@/assets/images/brutalist/Brutalism_71.png'),
    require('@/assets/images/brutalist/Brutalism_72.png'),
    require('@/assets/images/brutalist/Brutalism_73.png'),
    require('@/assets/images/brutalist/Brutalism_74.png'),
    require('@/assets/images/brutalist/Brutalism_75.png'),
    require('@/assets/images/brutalist/Brutalism_76.png'),
    require('@/assets/images/brutalist/Brutalism_77.png'),
    require('@/assets/images/brutalist/Brutalism_78.png'),
    require('@/assets/images/brutalist/Brutalism_79.png'),
    require('@/assets/images/brutalist/Brutalism_80.png'),
    require('@/assets/images/brutalist/Brutalism_81.png'),
    require('@/assets/images/brutalist/Brutalism_82.png'),
    require('@/assets/images/brutalist/Brutalism_83.png'),
    require('@/assets/images/brutalist/Brutalism_84.png'),
    require('@/assets/images/brutalist/Brutalism_85.png'),
    require('@/assets/images/brutalist/Brutalism_86.png'),
    require('@/assets/images/brutalist/Brutalism_87.png'),
    require('@/assets/images/brutalist/Brutalism_88.png'),
    require('@/assets/images/brutalist/Brutalism_89.png'),
    require('@/assets/images/brutalist/Brutalism_90.png'),
    require('@/assets/images/brutalist/Brutalism_91.png'),
    require('@/assets/images/brutalist/Brutalism_92.png'),
    require('@/assets/images/brutalist/Brutalism_93.png'),
    require('@/assets/images/brutalist/Brutalism_94.png'),
    require('@/assets/images/brutalist/Brutalism_95.png'),
    require('@/assets/images/brutalist/Brutalism_96.png'),
    require('@/assets/images/brutalist/Brutalism_97.png'),
    require('@/assets/images/brutalist/Brutalism_98.png'),
    require('@/assets/images/brutalist/Brutalism_99.png'),
    require('@/assets/images/brutalist/Brutalism_100.png'),
    require('@/assets/images/brutalist/Brutalism_101.png'),
    require('@/assets/images/brutalist/Brutalism_102.png'),
    require('@/assets/images/brutalist/Brutalism_103.png'),
    require('@/assets/images/brutalist/Brutalism_104.png'),
    require('@/assets/images/brutalist/Brutalism_105.png'),
    require('@/assets/images/brutalist/Brutalism_106.png'),
    require('@/assets/images/brutalist/Brutalism_107.png'),
    require('@/assets/images/brutalist/Brutalism_108.png'),
    require('@/assets/images/brutalist/Brutalism_109.png'),
    require('@/assets/images/brutalist/Brutalism_110.png'),
    require('@/assets/images/brutalist/Brutalism_111.png'),
    require('@/assets/images/brutalist/Brutalism_112.png'),
    require('@/assets/images/brutalist/Brutalism_113.png'),
    require('@/assets/images/brutalist/Brutalism_114.png'),
    require('@/assets/images/brutalist/Brutalism_115.png'),
    require('@/assets/images/brutalist/Brutalism_116.png'),
    require('@/assets/images/brutalist/Brutalism_117.png'),
    require('@/assets/images/brutalist/Brutalism_118.png'),
];

const allImages = [...abstractImages, ...bauhausImages, ...brutalismImages];

const colorPairs = [
    { tint: '#FFA617', background: '#0056B3' }, // Orange → Deep blue
    { tint: '#59C9DF', background: '#DC2626' }, // Cyan → Bold red
    { tint: '#C678FF', background: '#16A34A' }, // Purple → Forest green
    { tint: '#FF79D7', background: '#047857' }, // Pink → Teal green
    { tint: '#FFD800', background: '#4C1D95' }, // Yellow → Deep purple
    { tint: '#84E600', background: '#C026D3' }  // Lime → Magenta
];

function hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        const char = str.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash;
    }
    return Math.abs(hash);
}

export const AvatarBrutalist = React.memo((props: AvatarBrutalistProps) => {
    const { id, size = 32, square = false, monochrome = false } = props;

    const imageIndex = hashCode(id) % allImages.length;
    const colorIndex = hashCode(id + 'color') % colorPairs.length;

    const imageSource = allImages[imageIndex];
    const colorPair = colorPairs[colorIndex];
    const tintColor = monochrome ? '#999999' : colorPair.tint;
    const backgroundColor = monochrome ? '#F0F0F0' : colorPair.background;

    const dimension = square ? size : size;
    const borderRadius = square ? 0 : size / 2;

    return (
        <View
            style={{
                width: dimension,
                height: dimension,
                borderRadius,
                backgroundColor,
                // borderWidth: square ? 0 : 0.5,
                // borderColor: 'rgba(0, 0, 0, 0.1)',
                justifyContent: 'center',
                alignItems: 'center'
            }}
        >
            <Image
                source={imageSource}
                style={{
                    width: dimension * 0.8,
                    height: dimension * 0.8,
                    borderRadius
                }}
                tintColor={tintColor}
            />
        </View>
    );
});